name: VariableTesting
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    description: Name of the input topic to listen to.
    defaultValue: input_topic
  - name: output
    inputType: OutputTopic
    multiline: false
    description: Name of the output topic to write to.
    defaultValue: output-topic
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
