# Stage 1: Build the Angular application
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve the Angular application using Nginx
FROM nginx:1.25.3-bookworm
COPY --from=build /app/dist/angular-starter-template/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY run_server.sh /

RUN chmod +x /run_server.sh
RUN chown -R nginx:nginx /usr/share/nginx/html && chmod -R 755 /usr/share/nginx/html

CMD ["/run_server.sh"]
