name: postgresql
language: docker
variables:
  - name: POSTGRES_USER
    inputType: FreeText
    multiline: false
    description: The root username to initialize PostgreSQL with
    defaultValue: adminjj
    required: true
  - name: POSTGRES_PASSWORD
    inputType: Secret
    description: The root password to initialize MongoDB with
    defaultValue: ADMIN_PASSWORD
    required: true
  - name: POSTGRES_DB
    inputType: FreeText
    description: The default database name to initialize PostgreSQL with
    defaultValue: quix
    required: true
dockerfile: dockerfile
defaultFile: dockerfile
libraryItemId: postgresql
