name: React starter template
language: nodejs
variables:
  - name: input
    inputType: InputTopic
    description: The topic to pub/sub
    required: true
  - name: bearer_token
    inputType: FreeText
    description: Your bearer_token
    required: true
dockerfile: dockerfile
defaultFile: src/services/quix.ts
libraryItemId: dc712441-abf5-43b7-a7a2-ced9a3f9508b
