name: Basic React App
language: nodejs
variables:
  - name: input
    inputType: InputTopic
    description: The topic to read from
    defaultValue: hello-world-source
    required: true
  - name: bearer_token
    inputType: FreeText
  - name: testGroup1
    inputType: VariableGroup
    multiline: false
    description: Variable Group describing an InfluxDB connection. The selected value set's keys are injected as individual environment variables at runtime.
    variables:
      - key: INFLUXDB_HOST
        description: InfluxDB hostname.
      - key: INFLUXDB_PORT
        description: InfluxDB port.
      - key: INFLUXDB_TOKEN
        description: InfluxDB API token.
        secret: true
dockerfile: dockerfile
defaultFile: src/services/quix.ts
