name: VariableTesting
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    description: Name of the input topic to listen to.
    defaultValue: input_topic
  - name: output
    inputType: OutputTopic
    multiline: false
    description: Name of the output topic to write to.
    defaultValue: output-topic
  - name: FreeText
    inputType: FreeText
    multiline: false
    defaultValue: FreeText value
  - name: MultiLine
    inputType: FreeText
    multiline: true
    defaultValue: |
      MultiLine value
  - name: Options
    inputType: Options
    multiline: false
    description: jjj
    defaultValue: Different222
    options:
      - label: hellooooo
        value: hellooooo
      - label: Patrick
        value: Patrick222
      - label: Same
        value: Same
      - label: Different
        value: Different222
  - name: secret
    inputType: Secret
    multiline: false
    description: kkk
    defaultValue: INFLUXDB_ADMIN_TOKEN
    required: true
  - name: k
    inputType: FreeText
    multiline: false
    description: k
    defaultValue: kk
  - name: cc
    inputType: InputTopic
    multiline: false
    defaultValue: first_topic
  - name: group1
    inputType: VariableGroup
    description: Variable Group describing an InfluxDB connection. The selected value set's keys are injected as individual environment variables at runtime.
    variableGroupId: influxdb-demo
    variableGroupName: INFLUXDB_CONNECTION
    variableGroupDescription: Variable Group describing an InfluxDB connection. The selected value set's keys are injected as individual environment variables at runtime.
    variables:
      - key: INFLUXDB_HOST
        description: InfluxDB hostname.
      - key: INFLUXDB_PORT
        description: InfluxDB port.
      - key: INFLUXDB_TOKEN
        description: InfluxDB API token.
        secret: true
  - name: group2
    inputType: VariableGroup
    description: iii
    variableGroupId: redis-credentials
    variableGroupName: chrisTest
    variableGroupDescription: iii
    variables:
      - key: iii
        required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
