name: ingestion-api
language: nodejs
variables:
  - name: ff
    inputType: Secret
    multiline: false
    defaultValue: jjj
dockerfile: dockerfile
defaultFile: main.js
libraryItemId: nodejs-starter-template
