name: ingestion-api
language: nodejs
variables:
  - name: ff
    inputType: Secret
    multiline: false
    defaultValue: jjj
  - name: j
    inputType: Group
    multiline: false
    defaultValue: J
    variables:
      - key: j
        description: j
        defaultValue: j
        required: true
      - key: jj
        description: 888
        defaultValue: 8
        secret: true
        required: true
      - key: sxs
        description: 88
        defaultValue: 8
        secret: true
        required: true
dockerfile: dockerfile
defaultFile: main.js
libraryItemId: nodejs-starter-template
